// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD02s3d9--IUtySY-Tyfwgp-sSTBalt63A',
    appId: '1:249547916455:web:248eb79cc127c1b67dc782',
    messagingSenderId: '249547916455',
    projectId: 'drb-shipment-training',
    authDomain: 'drb-shipment-training.firebaseapp.com',
    storageBucket: 'drb-shipment-training.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz3WneitnaABQAuepvvDLy-_zxz-gLiRk',
    appId: '1:433288976185:android:dcd7a48afa42dc123afae8',
    messagingSenderId: '433288976185',
    projectId: 'drb-group-project',
    storageBucket: 'drb-group-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdLRHMqLp15RLewVOr8W9XPgvBEeAdbyI',
    appId: '1:433288976185:ios:2fec13fa603b2aab3afae8',
    messagingSenderId: '433288976185',
    projectId: 'drb-group-project',
    storageBucket: 'drb-group-project.firebasestorage.app',
    iosBundleId: 'com.example.drbShipmentUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvMiCOrxcrbR322nBgjIqLx-UH_q2YzRo',
    appId: '1:249547916455:ios:a91e13026057cdcc7dc782',
    messagingSenderId: '249547916455',
    projectId: 'drb-shipment-training',
    storageBucket: 'drb-shipment-training.firebasestorage.app',
    iosBundleId: 'com.example.drbShipmentUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD02s3d9--IUtySY-Tyfwgp-sSTBalt63A',
    appId: '1:249547916455:web:055952fe09869fd57dc782',
    messagingSenderId: '249547916455',
    projectId: 'drb-shipment-training',
    authDomain: 'drb-shipment-training.firebaseapp.com',
    storageBucket: 'drb-shipment-training.firebasestorage.app',
  );
}